_wandb:
    value:
        cli_version: 0.23.1
        e:
            sps866a00kio6kqwzm1m9qk7rdjzytse:
                codePath: any_percent_bc.py
                codePathLocal: any_percent_bc.py
                email: nityakas@usc.edu
                executable: /home/nityakas/any_percent_bc/.venv/bin/python3
                host: snoopy1
                os: Linux-5.15.0-83-generic-x86_64-with-glibc2.35
                program: /home/nityakas/any_percent_bc/any_percent_bc.py
                python: CPython 3.9.25
                root: /home/nityakas/any_percent_bc
                startedAt: "2026-01-01T03:45:41.878175Z"
                writerId: sps866a00kio6kqwzm1m9qk7rdjzytse
        m: []
        python_version: 3.9.25
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 13
                - 14
                - 16
            "4": 3.9.25
            "5": 0.23.1
            "12": 0.23.1
            "13": linux-x86_64
batch_size:
    value: 256
buffer_size:
    value: 2000000
checkpoints_path:
    value: null
device:
    value: cuda:5
discount:
    value: 0.99
env:
    value: halfcheetah-medium-expert-v2
eval_freq:
    value: 5000
frac:
    value: 0.1
group:
    value: BC-D4RL
load_model:
    value: ""
max_timesteps:
    value: 1000000
max_traj_len:
    value: 1000
n_episodes:
    value: 10
name:
    value: BC-halfcheetah-medium-expert-v2-cc5ec695
normalize:
    value: true
project:
    value: CORL
seed:
    value: 0
